web_site/models/Review_model.py
#!/usr/bin/python3
"""Reviews models"""
from web_site import db
from web_site import models


class Reviews(db.Model):
    """reveiws class"""
    id = db.Column(db.Integer, primary_key=True, unique=True)
    Book_id = db.Column(db.String(60), db.ForeignKey("books.id"), nullable=False)
    Bookname = db.Column(db.String(60), db.ForeignKey("books.title"), nullable=False)
    user_id = db.Column(db.String(60), db.ForeignKey("user.id"), nullable=False)
    username = db.Column(db.String(60), db.ForeignKey("user.name"), nullable=False)
    Review_text = db.Column(db.Text(1024), nullable=False)
    rating = db.Column(db.Integer, nullable=False, default=0)

web_site/models/contact.py
#!/usr/bin/pyhton3
"""Books Model"""
from web_site import db
from web_site import models

class Contact_us(db.Model):
    """contact us"""
    id = db.Column(db.Integer, primary_key=True, unique=True)
    name = db.Column(db.String(128))
    email = db.Column(db.String(128))
    phone_number = db.Column(db.Integer)
    message_box = db.Column(db.String(1024), nullable=False)

web_site/views/app_views.py
from flask import Blueprint, render_template, request, flash, jsonify, redirect, url_for
import json
from web_site import db, app
from web_site.models.Books_model import Books
from web_site.models.contact import Contact_us
from web_site.models.Category_model import Category
from web_site.models.Review_model import Reviews
from web_site.models.User_model import User
from flask_login import login_required, current_user

app_views = Blueprint('app_views', __name__)

@app_views.route('/', strict_slashes=False)
def landing():
    return render_template("landing.html")

@app_views.route('/Home', strict_slashes=False)
@login_required
def home():
    """home page"""
    #return jsonify({"success": True, "redirect": url_for('app_views.my_account')})
    return render_template("index.html")

@app_views.route('/About', strict_slashes=False)
def about():
    """About page"""
    return render_template("about.html")


@app_views.route('/Category', strict_slashes=False)
def category():
    categories = Category.query.all()
    
    return render_template("categories.html", categories=categories, title='categories')

@app_views.route('/book_by_category/<category_name>/', strict_slashes=False)
def list_books(category_name):
    categories = Category.query.filter_by(category_name=category_name).all()

    book = Books.query.filter_by(Catergory_name=category_name).all()
    

    return render_template('books_by_cat.html', book=book, categories=categories)


@app_views.route('/single_book/<int:book_id>', strict_slashes=False)
def single_book(book_id):
    book = Books.query.get(book_id)
    cat = book.Catergory_name
    img = book.img_link
    if book:
        return render_template('single_book.html', book=book, cat=cat, img=img, book_id=book.id)
    else:
        return ('NOT FOUND'), 404

@app_views.route('/books', strict_slashes=False)
def books():
    books = Books.query.all()

    return render_template("books.html", books=books)

@app_views.route('/review/<int:book_id>', methods=['GET', 'POST'], strict_slashes=False)
def review(book_id):
    book = Books.query.get(book_id)
    if request.method == 'POST':
        data = request.get_json()
        review_text = data.get('review_text')
        rating = int(data.get('rating'))
        
        if book:
            new_review = Reviews(
                Book_id=book.id,
                Bookname=book.title,
                user_id=current_user.id,
                username=current_user.name,
                Review_text=review_text,
                rating=rating
            )

            db.session.add(new_review)
            db.session.commit()

            db.session.close()
            flash('Review posted successfully!', category='success')
            return jsonify({"success": True, "redirect": url_for('app_views.post_review')})
        else:
            flash("No book found")

    return render_template('review.html', book=book)

@app_views.route('/post_review',  strict_slashes=False)
@login_required
def post_review():
    list_reviews = Reviews.query.all()

    return render_template("all_reviews.html", list_reviews=list_reviews)

@app_views.route('/My_account',  strict_slashes=False)
@login_required
def my_account():
    user = User.query.get(current_user.id)
    user_id = user.id
    q = Reviews.query.filter_by(user_id=current_user.id).all()
    return render_template("my_account.html", user=user, q=q )

@app_views.route('/contact-us', strict_slashes=False, methods=['GET', 'POST'])
def contact_us():
    if request.method == 'POST':
        data = request.get_json()
        name1 = data.get('name')
        email1 = data.get('email')
        phone = data.get('phone_number')
        message_box = data.get('message_box')

        new_details = Contact_us(name=name1, email=email1, phone_number=phone, message_box=message_box)
        db.session.add(new_details)
        db.session.commit()
        db.session.close()
        return jsonify({'success': True, 'redirect': url_for('app_views.home')})
    
    return render_template("contact.html")

web_site/views/login.py
""" website """
from flask import Flask, Blueprint, render_template, request, redirect, url_for
from flask import flash, jsonify
from web_site.models.User_model import User
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, login_required, logout_user, current_user
from web_site  import db, app
from web_site import models
from web_site.views import app_views

app_login = Blueprint('app_login', __name__)


@app_login.route('/login', strict_slashes=False, methods=['GET', 'POST'])
def login_method():
    """method to log in"""
    if request.method == 'POST':
        data = request.get_json()
        email = data.get('email')
        password1 = data.get('password')
        user = User.query.filter_by(email=email).first()
        if user:
            if user.password == password1:
                flash('LOGGED IN!', category="success")
                login_user(user, remember=True)
                return jsonify({'success': True, 'redirect': url_for('app_views.home')})
            else:
                flash('incorrect account details', category="error")
        else:
            flash('No Record', category="error")
    return render_template("login.html", user=current_user)

@app_login.route('/logout', strict_slashes=False)
def logout_method():
    """logs user out"""
    logout_user()
    return redirect(url_for('app_login.login_method'))

@app_login.route('/sign-up', strict_slashes=False, methods=['GET','POST'])
def sign_up_method():
    if request.method == 'POST':
        data = request.get_json()
        name1 = data.get('name')
        surname1 = data.get('surname')
        email1 = data.get('email')
        password1 = data.get('password')

        user = User.query.filter_by(email=email1).first()
        if user:
            flash('Email already exists.')
        else:
            new_user = User(email=email1, name=name1,surname=surname1, password=password1)
            db.session.add(new_user)
            db.session.commit()
            db.session.refresh(new_user)

            db.session.close()
            login_user(new_user, remember=True)
            flash('Account created!', category='success')
            return jsonify({'success': True, 'redirect': url_for('app_login.login_method')})

    return render_template("Register.html", user=current_user)

web_site/templates/books.html
<!DOCTYPE html>
<html>

<head>
  <!-- Basic -->
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <!-- Mobile Metas -->
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <!-- Site Metas -->
  <link rel="icon" href="../../static/styles/images/favicon.png" type="image/gif" />
  <meta name="keywords" content="" />
  <meta name="description" content="" />
  <meta name="author" content="" />

  <title>Books</title>

  <!-- bootstrap core css -->
  <link rel="stylesheet" type="text/css" href="../../static/styles/bootstrap.css" />
  <!-- font awesome style -->
  <link href="../../static/styles/font-awesome.min.css" rel="stylesheet" />

  <!-- Custom styles for this template -->
  <link href="../../static/styles/style.css" rel="stylesheet" />
  
  <!-- responsive style -->
  <link href="../../static/styles/responsive.css" rel="stylesheet" />

</head>
<body>

    <div class="hero_area">
      <!-- header section strats -->
      <header class="header_section">
        <div class="container-fluid">
          <nav class="navbar navbar-expand-lg custom_nav-container ">
            <a class="navbar-brand" href="index.html">
              <span>
                eBook Club
              </span>
            </a>
  
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class=""> </span>
            </button>
  
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav">
                <li class="nav-item">
                  <a class="nav-link" href="{{ url_for('app_views.home')}}"> Home </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{{ url_for('app_views.about')}}"> About</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{{ url_for('app_views.category')}}">Categories</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{{ url_for('app_views.post_review')}}"> Reviews </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="contact.html">Contact Us</a>
                </li>
              </ul>
            </div>
          </nav>
        </div>
      </header>
      <!-- end header section -->
    <!--slide show-->
    <section class="slider_section ">
      <div id="customCarousel1" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
          <div class="carousel-item active">
            <div class="container ">
              <div class="row">
                <div class="col-md-6">
                  <div class="img-box">
                    <img src="../../static/styles/images/full_measures.jpeg" alt="">
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="img-box">
                    <img src="../../static/styles/images/the_bee_sting.jpeg" alt="">
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="carousel-item ">
            <div class="container ">
              <div class="row">
                <div class="col-md-6">
                  <div class="img-box">
                    <img src="../../static/styles/images/beyond.jpeg" alt="">
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="img-box">
                    <img src="../../static/styles/images/Rebel.jpeg" alt="">
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="carousel-item ">
            <div class="container ">
              <div class="row">
                <div class="col-md-6">
                  <div class="img-box">
                    <img src="../../static/styles/images/Rise.jpeg" alt="">
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="img-box">
                    <img src="../../static/styles/images/random_death.jpeg" alt="">
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="carousel-item ">
            <div class="container ">
              <div class="row">
                <div class="col-md-6">
                  <div class="img-box">
                    <img src="../../static/styles/images/dark_places.jpeg" alt="">
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="img-box">
                    <img src="../../static/styles/images/encore.jpeg" alt="">
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
          <div class="carousel-item ">
            <div class="container ">
              <div class="row">
                <div class="col-md-6">
                  <div class="img-box">
                    <img src="../../static/styles/images/first_lie.jpeg" alt="">
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="img-box">
                    <img src="../../static/styles/images/tales_of_honor.jpeg" alt="">
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="carousel-item ">
            <div class="container ">
              <div class="row">
                <div class="col-md-6">
                  <div class="img-box">
                    <img src="../../static/styles/images/blade_runner.jpeg" alt="">
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="img-box">
                    <img src="../../static/styles/images/blade_runner.jpeg" alt="">
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="carousel_btn_box">
          <a class="carousel-control-prev" href="#customCarousel1" role="button" data-slide="prev">
            <i class="fa fa-angle-left" aria-hidden="true"></i>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#customCarousel1" role="button" data-slide="next">
            <i class="fa fa-angle-right" aria-hidden="true"></i>
            <span class="sr-only">Next</span>
          </a>
        </div>
      </div>
    </section>
    <!-- end slider section -->

              
      <!-- books section-->
      <section class="catagory_section layout_padding">
        <div class="catagory_container">
          <div class="container ">
            <div class="heading_container heading_center">
              <h2>
                <strong>Books</strong>
              </h2>
              <p>Lets explore through literature!</p>
            </div>
            <div class="detail-box">
                        {% for book in books %}
                        <ul>
            <li><a href="{{ url_for('app_views.single_book', book_id=book.id) }}"><strong>{{ book.title }}</strong></a></li>
            </ul>
                        {% endfor %}
            </div>
            </div>
        </div>
    </section> 
      <!-- info section -->

  <section class="info_section layout_padding2">
    <div class="container">
      <div class="row">
        <div class="col-md-6 col-lg-3 info-col">
          <div class="info_detail">
            <h4>
              About Us
            </h4>
            <p>
              Vitae aut explicabo fugit facere alias distinctio, exem commodi mollitia minusem dignissimos atque asperiores incidunt vel voluptate iste
            </p>
            <div class="info_social">
              <a href="">
                <i class="fa fa-facebook" aria-hidden="true"></i>
              </a>
              <a href="">
                <i class="fa fa-twitter" aria-hidden="true"></i>
              </a>
              <a href="">
                <i class="fa fa-linkedin" aria-hidden="true"></i>
              </a>
              <a href="">
                <i class="fa fa-instagram" aria-hidden="true"></i>
              </a>
            </div>
          </div>
        </div>
        <div class="col-md-6 col-lg-3 info-col">
          <div class="info_contact">
            <h4>
              Address
            </h4>
            <div class="contact_link_box">
              <a href="">
                <i class="fa fa-map-marker" aria-hidden="true"></i>
                <span>
                  Location
                </span>
              </a>
              <a href="">
                <i class="fa fa-phone" aria-hidden="true"></i>
                <span>
                  Call +01 1234567890
                </span>
              </a>
              <a href="">
                <i class="fa fa-envelope" aria-hidden="true"></i>
                <span>
                  demo@gmail.com
                </span>
              </a>
            </div>
          </div>
        </div>
        <div class="col-md-6 col-lg-3 info-col">
          <div class="info_contact">
            <h4>
              Newsletter
            </h4>
            <form action="#">
              <input type="text" placeholder="Enter email" />
              <button type="submit">
                Subscribe
              </button>
            </form>
          </div>
        </div>
              </div>
    </div>
  </section>

  <!-- end info section -->
  <!-- footer section -->
  <footer class="footer_section">
    <div class="container">
      <p>
        &copy; <span id="displayYear"></span>  EBOOKCLUB All Rights Reserved By
      </p>
    </div>
  </footer>
  <!-- footer section -->

  <!-- jQery -->
  <script src="../../static/styles/jquery-3.4.1.min.js"></script>
  <!-- bootstrap js -->
  <script src="../../static/styles/bootstrap.js"></script>
  <!-- custom js -->
  <script src="../../static/styles/custom.js"></script>
  

</body>

</html>

web_site/templates/books_by_cat.html
<!DOCTYPE html>
<html>

<head>
  <!-- Basic -->
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <!-- Mobile Metas -->
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <!-- Site Metas -->
  <link rel="icon" href="../../static/styles/images/favicon.png" type="image/gif" />
  <meta name="keywords" content="" />
  <meta name="description" content="" />
  <meta name="author" content="" />

  <title>Books by Category</title>

  <!-- bootstrap core css -->
  <link rel="stylesheet" type="text/css" href="../../static/styles/bootstrap.css" />
  <!-- font awesome style -->
  <link href="../../static/styles/font-awesome.min.css" rel="stylesheet" />

  <!-- Custom styles for this template -->
  <link href="../../static/styles/style.css" rel="stylesheet" />
  <link href="../../static/styles/review.css" rel="stylesheet" />
  <!-- responsive style -->
  <link href="../../static/styles/responsive.css" rel="stylesheet" />

</head>

<body class="sub_page">

  <div class="hero_area">
    <!-- header section strats -->
    <header class="header_section">
      <div class="container-fluid">
        <nav class="navbar navbar-expand-lg custom_nav-container ">
          <a class="navbar-brand" href="{{ url_for('app_views.home')}}">
            <span>
              eBook Club
            </span>
          </a>

          
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('app_views.home')}}"> Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('app_views.about')}}"> About</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('app_views.contact_us')}}">Contact Us</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('app_login.login_method')}}"> Logout</a>
              </li>
            </ul>
          </div>
        </nav>
      </div>
    </header>
    <!-- end header section -->
  </div>

  <!-- book by category page section -->
  <section class="catagory_section layout_padding">
    <div class="catagory_container">
      <div class="container ">
        <div class="heading_container heading_center">
        {% for c in categories%}
          <h2>
           {{c.category_name }}
          </h2>
        {% endfor %}
          <p>
            Each category represents a specific type of literature, <br>
            allowing readers to explore a diverse range of topics, writing styles, and storytelling approaches.
          </p>
        </div>
        <div class="row">
            {% for b in book %}
                <div class="col-sm-6 col-md-4 ">
                    <div class="box ">
                        <div class="img-box">
                            <img src="../../static/styles/images/cat2.png" alt="">
                          </div>
                     <div class="detail-box">
                        <li>
                            <a href="{{ url_for('app_views.single_book', book_id=b.id) }}"><h5><strong>{{ b.title }}</strong> by {{ b.Author }}</h5></a>
                        </li>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
    
  </section>
  <!-- info section -->

  <section class="info_section layout_padding2">
    <div class="container">
      <div class="row">
        <div class="col-md-6 col-lg-3 info-col">
          <div class="info_detail">
            <h4>
              About Us
            </h4>
            <p>
            An online book club platform that brings book enthusiasts together to explore, review, and discuss their favorite literary works.
            </p>
            <div class="info_social">
              <a href="">
                <i class="fa fa-facebook" aria-hidden="true"></i>
              </a>
              <a href="">
                <i class="fa fa-twitter" aria-hidden="true"></i>
              </a>
              <a href="">
                <i class="fa fa-linkedin" aria-hidden="true"></i>
              </a>
              <a href="">
                <i class="fa fa-instagram" aria-hidden="true"></i>
              </a>
            </div>
          </div>
        </div>
        <div class="col-md-6 col-lg-3 info-col">
          <div class="info_contact">
            <h4>
              Address
            </h4>
            <div class="contact_link_box">
              <a href="">
                <i class="fa fa-map-marker" aria-hidden="true"></i>
                <span>
                  Location
                </span>
              </a>
              <a href="">
                <i class="fa fa-phone" aria-hidden="true"></i>
                <span>
                  Call +01 1234567890
                </span>
              </a>
              <a href="">
                <i class="fa fa-envelope" aria-hidden="true"></i>
                <span>
                  demo@gmail.com
                </span>
              </a>
            </div>
          </div>
        </div>
        <div class="col-md-6 col-lg-3 info-col">
          <div class="info_contact">
            <h4>
              Newsletter
            </h4>
            <form action="#">
              <input type="text" placeholder="Enter email" />
              <button type="submit">
                Subscribe
              </button>
            </form>
          </div>
        </div>
        <div class="col-md-6 col-lg-3 info-col">
          <div class="map_container">
            <div class="map">
              <div id="googleMap"></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- end info section -->

  <!-- footer section -->
  <footer class="footer_section">
    <div class="container">
        <p>
            &copy; <span id="displayYear"></span> EBOOKCLUB All Rights Reserved By
        </p>
    </div>
  </footer>
  <!-- footer section -->

  <!-- jQery -->
  <script src="../../static/styles/jquery-3.4.1.min.js"></script>
  <!-- bootstrap js -->
  <script src="../../static/styles/bootstrap.js"></script>
  <!-- custom js -->
  <script src="../../static/styles/custom.js"></script>
  <!-- login js -->
  <script src="../../static/styles/review.js"></script>
  

</body>

</html>

web_site/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!--<link rel="stylesheet" type="text/css" href="../static/styles/categorie.css">-->
    <link rel="stylesheet" type="text/css" href="../static/styles/books.css">
    <link rel="stylesheet" type="text/css" href="../static/styles/review.css">
    <link rel="stylesheet" type="text/css" href="../static/styles/index.css">
    <link rel="stylesheet" type="text/css" href="../static/styles/login.css">
    <link rel="stylesheet" type="text/css" href="../static/styles/my_account.css">
    <link rel="stylesheet" type="text/css" href="../static/styles/single_book.css">
    <link rel="stylesheet" type="text/css" href="../static/styles/single.css">
    <link rel="icon" href="static/images/Ebooklogo.png" type="image/png" class="ebook-logo">
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
<title>{{ title }}</title>
</head>
<body>
    {% block body %}{% endblock %}
</body>
</html>

web_site/templates/single_book.html
<!DOCTYPE html>
<html>

<head>
  <!-- Basic -->
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <!-- Mobile Metas -->
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <!-- Site Metas -->
  <link rel="icon" href="../../static/styles/images/favicon.png" type="image/gif" />
  <meta name="keywords" content="" />
  <meta name="description" content="" />
  <meta name="author" content="" />

  <title>Book page</title>

  <!-- bootstrap core css -->
  <link rel="stylesheet" type="text/css" href="../../static/styles/bootstrap.css" />
  <!-- font awesome style -->
  <link href="../../static/styles/font-awesome.min.css" rel="stylesheet" />

  <!-- Custom styles for this template -->
  <link href="../../static/styles/style.css" rel="stylesheet" />
  <!-- responsive style -->
  <link href="../../static/styles/responsive.css" rel="stylesheet" />

</head>

<body class="sub_page">

  <div class="hero_area">
    <!-- header section strats -->
    <header class="header_section">
      <div class="container-fluid">
        <nav class="navbar navbar-expand-lg custom_nav-container ">
          <a class="navbar-brand" href="{{ url_for('app_views.home')}}">
            <span>
              eBook Club
            </span>
          </a>

          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class=""> </span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link pl-lg-0" href="{{ url_for('app_views.home')}}">Home </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('app_views.about')}}"> About</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('app_views.category')}}">Categories</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('app_views.contact_us')}}">Contact Us</a>
              </li>
            </ul>
          </div>
        </nav>
      </div>
    </header>
    <!-- end header section -->
  </div>

  <!-- single page section -->
  <section class="single_page">
    <div class="container_page">
        <div class="row">
            <div class="col-md-6">
                <div class="img-box">
                    <img src="{{ img }}" alt="picture me">
                </div>
            </div>
            <div class="col-md-6">
                <div class="book-details">
                <div class="heading_container">
                    <h2>{{ book.title }}</h2>
                </div>
                <p><strong>Author: {{ book.Author }}</strong></p>
                <p><strong>Category: {{ book.Catergory_name }}</strong></p>
                <p><strong>Description:</strong> {{ book.Book_description }}</p>
                <p> Where to find the full book: <a href="{{book.ref_link}}">Here</a></p>
                <a href="{{ url_for('app_views.books') }}">Back to Books List</a>
                <a href="{{ url_for('app_views.review', book_id=book.id) }}">Add Review</a>
        
                </div>
            </div>
        </div>
    </div>
  </section>

  

  <!-- single page section -->

  <!-- info section -->

  <section class="info_section layout_padding2">
    <div class="container">
      <div class="row">
        <div class="col-md-6 col-lg-3 info-col">
          <div class="info_detail">
            <h4>
              About Us
            </h4>
            <p>
            An online book club platform that brings book enthusiasts together to explore, review, and discuss their favorite literary works.
            </p>
            <div class="info_social">
              <a href="">
                <i class="fa fa-facebook" aria-hidden="true"></i>
              </a>
              <a href="">
                <i class="fa fa-twitter" aria-hidden="true"></i>
              </a>
              <a href="">
                <i class="fa fa-linkedin" aria-hidden="true"></i>
              </a>
              <a href="">
                <i class="fa fa-instagram" aria-hidden="true"></i>
              </a>
            </div>
          </div>
        </div>
        <div class="col-md-6 col-lg-3 info-col">
          <div class="info_contact">
            <h4>
              Address
            </h4>
            <div class="contact_link_box">
              <a href="">
                <i class="fa fa-map-marker" aria-hidden="true"></i>
                <span>
                  Location
                </span>
              </a>
              <a href="">
                <i class="fa fa-phone" aria-hidden="true"></i>
                <span>
                  Call +01 1234567890
                </span>
              </a>
              <a href="">
                <i class="fa fa-envelope" aria-hidden="true"></i>
                <span>
                  demo@gmail.com
                </span>
              </a>
            </div>
          </div>
        </div>
        <div class="col-md-6 col-lg-3 info-col">
          <div class="info_contact">
            <h4>
              Newsletter
            </h4>
            <form action="#">
              <input type="text" placeholder="Enter email" />
              <button type="submit">
                Subscribe
              </button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- end info section -->

  <!-- footer section -->
  <footer class="footer_section">
    <div class="container">
      <p>
        &copy; <span id="displayYear"></span> EBOOKCLUB All Rights Reserved By
      </p>
    </div>
  </footer>
  <!-- footer section -->

  <!-- jQery -->
  <script src="../../static/styles/jquery-3.4.1.min.js"></script>
  <!-- bootstrap js -->
  <script src="../../static/styles/bootstrap.js"></script>
  <!-- custom js -->
  <script src="../../static/styles/custom.js"></script>

</body>

</html>